StockManagementSystemMVCWebApp/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StockManagementSystemMVCWebApp.Manager;
using StockManagementSystemMVCWebApp.Models;

namespace StockManagementSystemMVCWebApp.Controllers
{
    public class ItemController : Controller
    {
        public CategoryManager CategoryManager { get; set; }
        public CompanyManager CompanyManager { get; set; }
        public ItemManager ItemManager { get; set; }

        public ItemController()
        {
            CategoryManager=new CategoryManager();
            CompanyManager=new CompanyManager();
            ItemManager=new ItemManager();
        }
        //
        // GET: /Item/
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Save()
        {
            ViewBag.categoryList = CategoryManager.GetAllCategories();
            ViewBag.companyList = CompanyManager.GetAllCompanys();
            ViewBag.itemList = ItemManager.GetAllItems();
            return View();
        }

        [HttpPost]
        public ActionResult Save(Item item)
        {
            if (ModelState.IsValid)
            {
                ViewBag.message = ItemManager.Save(item);
            }
            else
            {
                ViewBag.message = "Model state is not valid";
            }
            

            ViewBag.categoryList = CategoryManager.GetAllCategories();
            ViewBag.companyList = CompanyManager.GetAllCompanys();
            ViewBag.itemList = ItemManager.GetAllItems();
            return View();
        }

        [HttpGet]
        public ActionResult SockIn()
        {
            ViewBag.companyList = CompanyManager.GetAllCompanys();
            return View();
        }

        [HttpPost]
        public ActionResult SockIn(Item item)
        {
            if (ModelState.IsValid)
            {
                ViewBag.message = ItemManager.UpdateQuantity(item);
            }
            else
            {
                ViewBag.message = "Model State is not Valid";
            }
            ViewBag.companyList = CompanyManager.GetAllCompanys();
            return View();
        }

        //It is by Page Load
        [HttpGet]
        public ActionResult Report()
        {
            ViewBag.categoryList = CategoryManager.GetAllCategories();
            ViewBag.companyList = CompanyManager.GetAllCompanys();
            ViewBag.itemList = null;
            return View();
        }

        [HttpPost]
        public ActionResult Report(Item item)
        {
            if (ModelState.IsValid)
            {

                ViewBag.itemList = ItemManager.GetAllItemsForReport(item);
            }
            else
            {
                ViewBag.itemList = null;
                ViewBag.message = "Model state is not valid";
            }

            ViewBag.categoryList = CategoryManager.GetAllCategories();
            ViewBag.companyList = CompanyManager.GetAllCompanys();
            //ViewBag.itemList = ItemManager.GetAllItemsForReport(item);
            return View();
        }

        //It is by Ajax
        public ActionResult ReportTwo()
        {
            ViewBag.categoryList = CategoryManager.GetAllCategories();
            ViewBag.companyList = CompanyManager.GetAllCompanys();
            return View();
        }

        public JsonResult GetItemsByCompanyId(int comId)
        {
            List<Item> itemList = ItemManager.GetItemsByCompanyId(comId);
            return Json(itemList);
        }

        public JsonResult GetInfoByItemId(int id)
        {
            Item item = ItemManager.GetInfoByItemId(id);
            return Json(item);
        }

        public JsonResult GetAllItemsForReportTwo(int comId, int cotId)
        {
            Item item =new Item();
            item.CompanyId = comId;
            item.CategoryId = cotId;
            List<Item> itemList = ItemManager.GetAllItemsForReport(item);
            foreach (Item i in itemList)
            {
                i.CompanyName = CompanyManager.GetCompanyNameTwo(i.CompanyId);
            }
            return Json(itemList);
        }
	}
}

StockManagementSystemMVCWebApp/Controllers/StockOutController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StockManagementSystemMVCWebApp.Manager;
using StockManagementSystemMVCWebApp.Models;

namespace StockManagementSystemMVCWebApp.Controllers
{
    public class StockOutController : Controller
    {
        public CompanyManager  CompanyManager { get; set; }
        public ItemManager ItemManager { get; set; }
        public StockOutManager StockOutManager { get; set; }

        public StockOutController()
        {
            CompanyManager = new CompanyManager();
            ItemManager=new ItemManager();
            StockOutManager=new StockOutManager();
        }
        //
        // GET: /StockOut/
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Save()
        {
            ViewBag.companyList = CompanyManager.GetAllCompanys();
            return View();
        }

        [HttpPost]
        public ActionResult Save(List<Item> items)
        {
            ViewBag.companyList = CompanyManager.GetAllCompanys();
            return View();
        }

        public ActionResult SaveNew()
        {
            ViewBag.companyList = CompanyManager.GetAllCompanys();
            return View();
        }

        public JsonResult SaveStockOut(int iId, int quantity, string oAction)
        {
            StockOut stockOut=new StockOut();
            stockOut.ItemId = iId;
            stockOut.Quantity = quantity;
            stockOut.OutAction = oAction;
            stockOut.ItemName = ItemManager.GetItemName(iId);
            stockOut.CompanyName = CompanyManager.GetCompanyName(iId);
            stockOut.Msg = StockOutManager.Save(stockOut);
            return Json(stockOut);
        }
        public ActionResult OutReport()
        {
            return View();
        }

        public JsonResult GetReportByDates(string fodate, string todate)
        {
            List<StockOut> stockoutList = StockOutManager.GetReportDates(fodate, todate);
            foreach (StockOut i in stockoutList)
            {
                i.ItemName = ItemManager.GetItemName(i.ItemId);
            }
            return Json(stockoutList);
        }
        public JsonResult GetItemsByCompanyId(int comId)
        {
            List<Item> itemList = ItemManager.GetItemsByCompanyId(comId);
            return Json(itemList);
        }
        public JsonResult GetInfoByItemId(int id)
        {
            Item item = ItemManager.GetInfoByItemId(id);
            return Json(item);
        }

        public ActionResult Save_Update()
        {
            ViewBag.companyList = CompanyManager.GetAllCompanys();
            return View();
        }
        [HttpPost]
        public ActionResult Save_Update(StockOut stockOut)
        {
            if (Session["OutList"] == null)
            {
                List<StockOut> s = new List<StockOut>();

                //stockOut.ItemId = iId;
                //stockOut.Quantity = quantity;
                //stockOut.OutAction = oAction;
                stockOut.ItemName = ItemManager.GetItemName(stockOut.ItemId);
                stockOut.CompanyName = CompanyManager.GetCompanyName(stockOut.ItemId);


                s.Add(stockOut);
                Session["OutList"] = s;
            }
            else
            {
                stockOut.ItemName = ItemManager.GetItemName(stockOut.ItemId);
                stockOut.CompanyName = CompanyManager.GetCompanyName(stockOut.ItemId);
                var userList = (List<StockOut>)Session["OutList"];
                userList.Add(stockOut);
                Session["OutList"] = userList;

            }
            ViewBag.companyList = CompanyManager.GetAllCompanys();
            return View();
        }

        [HttpPost]
        public ActionResult ListSave()
        {
            var userList = (List<StockOut>)Session["OutList"];
            Session["OutList"] = null;
            foreach (var stockOut in userList)
            {
                stockOut.Msg = StockOutManager.Save(stockOut);
            }

            return RedirectToAction("Save_Update");
        }

        public JsonResult GetInfoByItemId_Update(int id)
        {
            Item item = ItemManager.GetInfoByItemId(id);
            if (Session["OutList"] != null)
            {
                List<StockOut> userList = (List<StockOut>)Session["OutList"];
                foreach (StockOut stockOut in userList)
                {
                    if (item.Id==stockOut.ItemId)
                    {
                        item.AvailableQuantity = item.AvailableQuantity - stockOut.Quantity;
                    }
                }
            }
            return Json(item);
        }
	}
}

StockManagementSystemMVCWebApp/Views/Shared/_LOut.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/stylemvc.css" rel="stylesheet"/>
    <style>
        h2 {
            color: black;
        }
    </style>
    @RenderSection("style",required:false)
</head>
<body>
    <div class="headerSection templete clear">
        <h2>Stock Management System</h2>
    </div>
<div class="navSection templete">
    <ul>
        <li><a href="@Url.Action("Save","Category")">Category</a></li>
        <li><a href="@Url.Action("Save","Company")">Company</a></li>
        <li><a href="@Url.Action("Save","Item")">Item</a></li>
        <li>
            <a href="#">Stock</a>
            <ul>
                <li><a href="@Url.Action("SockIn", "Item")">Stock In</a></li>
                <li><a href="@Url.Action("Save_Update", "StockOut")">Stock Out</a></li>
            </ul>
        </li>
        <li><a href="@Url.Action("ReportTwo", "Item")">Search</a></li>
        <li><a href="@Url.Action("OutReport", "StockOut")">Report</a></li>
    </ul>
</div>

    <div class="mainSection templete clear">
        <div class="mainSectionTemp clear"></div>

        <div class="mainSectionTwo clear">
            @RenderBody()
        </div>

    </div>

    <div class="footerSection templete clear">
        <p class="clear">&copy; Copyright 2019.</p>
    </div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

StockManagementSystemMVCWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>